language: python

python:
  - 3.6

cache:
  pip: true
  directories:
    - node_modules

install:
  - yarn add serverless

jobs:
  include:
    - stage: test
      script: python -m unittest
    - stage: deploy
      script: npm run serverless --version