service: moovement-test-app

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: python3.6
  memorySize: 128
  profile: moovement
  timeout: 5s

functions:
  greet:
    handler: hello_handler.handle
    events:
      - http:
          integration: lambda-proxy
          path: ""
          method: get
